services:
  - type: web
    name: easystones
    env: node
    buildCommand: npm install --production=false && npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.19.0
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        value: onboarding@resend.dev
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://easystones.onrender.com
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
